{% set name = "smbprotocol" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8102adfea6750a29c7e1a99edc58931a5ff948a659f17abc1f43cfc16ea17b6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cryptography >=2.0
    - pyspnego
    - six
  run_constrained:
    - python-gssapi >=1.4.1

test:
  imports:
    - smbprotocol

about:
  home: https://github.com/jborean93/smbprotocol
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interact with a server using the SMB 2/3 Protocol
  doc_url: https://github.com/jborean93/smbprotocol
  dev_url: https://github.com/jborean93/smbprotocol

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
